### ISSUE TITLE
Upgrade to LightInject 5.0.0

### ISSUE THREAD

**Issue by stefan505** [seesharper/LightInject.xUnit#3]
I forked this repo and attempted it myself, but these lines are problematic and I'm not sure how to fix it:

https://github.com/seesharper/LightInject.xUnit/blob/master/src/LightInject.xUnit2/LightInject.xUnit2.cs#L91
https://github.com/seesharper/LightInject.xUnit/blob/master/src/LightInject.xUnit2/LightInject.xUnit2.cs#L93
https://github.com/seesharper/LightInject.xUnit/blob/master/src/LightInject.xUnit2/LightInject.xUnit2.cs#L123
https://github.com/seesharper/LightInject.xUnit/blob/master/src/LightInject.xUnit2/LightInject.xUnit2.cs#L125

**Comment by seesharper** [comment]
Let me have a look at it

**Comment by seesharper** [comment]
Fixed and pushed to Nuget :)

**Comment by stefan505** [comment]
You're a machine, thanks!
